#
# Module manifest for module 'MagicEden-API'
#
# Generated by: lemons
#
# Generated on: 2/21/2022
#

@{

# Script module or binary module file associated with this manifest.
RootModule = 'MagicEden-API.psm1'

# Version number of this module.
ModuleVersion = '0.0.1'

# Supported PSEditions
# CompatiblePSEditions = @()

# ID used to uniquely identify this module
GUID = '20f85e44-577c-4d76-b1ab-321c86c1a0dd'

# Author of this module
Author = 'lemons'

# Company or vendor of this module
CompanyName = 'Unknown'

# Copyright statement for this module
Copyright = '(c) lemons. All rights reserved.'
FunctionsToExport = @()
CmdletsToExport = @()
VariablesToExport = '*'
AliasesToExport = @()
}

